### ISSUE TITLE
Using the beast 2.6 path sampler xml on beast 2.7 gives unhelpful error messages that are hard to debug

### ISSUE THREAD

**Issue by jordandouglas** [BEAST2-Dev/model-selection#12]
Regarding the BFD* tutorial for beast 2.6 which suggests you add this block of code to the xml:

```
<run spec=‘beast.inference.PathSampler’
chainLength="1000"
alpha=‘0.3’
rootdir=‘/home/desktop/BFD*-tutorial/runA/’
burnInPercentage=‘0’
preBurnin="0"
deleteOldLogs=‘true’
nrOfSteps=‘24’>
cd $(dir)
java -cp $(java.class.path) beast.app.beastapp.BeastMain $(resume/overwrite) -java -seed $(seed) beast.xml
```

If you fail to correct ``beast.inference.PathSampler`` to ``modelselection.inference.PathSampler`` (which I just did and I suspect most users will also do), then it would make sense to see an error which reads "cannot find beast.inference.PathSampler, did you mean modelselection.inference.PathSampler?"

However, instead of this I got the error message: 

```
java.io.FileNotFoundException: /home/desktop/BFD*-tutorial/runA/step0/mcmc.xml (No such file or directory)
```

which made the problem much more difficult to debug. 

I just wonder if there is a way of making this issue easier for futrue users to fix when they inevitably encounter it

**Comment by rbouckaert** [comment]
How can I reproduce the error message you got?

Once the spec attributes are adjusted (e.g., by running [migrate.pl](https://github.com/CompEvol/beast2/commits/master/scripts/migrate.pl) on the `runA.xml` file that comes with the tutorial), I get `java.lang.Exception: Directory /home/Desktop/BFD*-tutorial/runA/ does not exist and could not be created.`.

**Comment by jordandouglas** [comment]
I did not run migrate.pl, I incorporated the xml snippet above into an existing beast 2.7 xml file. But I used a different rootdir ``/tmp/`` rather than the default one

**Comment by rbouckaert** [comment]
When I change the rootdir to start with `tmp` it just runs on OS X. Perhaps the error message is due to the asterisk in the directory name on Linux?
